classes/stage: fix use of int() on None
Fixes:
 TypeError: int() argument must be a string or a number, not 'NoneType'
When building gettext
(cherry picked from commit 37bdaf6f28162bd849a447359a7f2b73025d0b8f)