class/core: runstrip() print error if filtype can not be determined
Prints readable error message instead of the following:
   File "/src/oe-lite/meta/core/classes/core.oeclass", line 147, in runstrip
     if "not stripped" not in filetype:
TypeError: argument of type 'NoneType' is not iterable

The actual cause of this error is unknown. The magic python module do not raise
an exception when file is not readable, but returns a NoneType object 'None'.

(cherry picked from commit 7136a49a0dccff383e7a5b6df6aaca2d2756ed67)